### ISSUE TITLE
OSX requires 'chmod +x debug\ game.sh' to run debug game.sh

### ISSUE THREAD

**Issue by bakpakin** [Planimeter/grid-sdk#50]
On OSX, and probably Linux, I had to chmod +x the love executable before I could run the script. While easy to do, It would be nice if the shell scripts did this themselves.

**Comment by ryan-kingstone** [comment]
We will implement a fix for this issue shortly.

**Comment by andrewmcwatters** [comment]
I'm at church, can you push this change to `grid-sdk` and I'll promote it upstream?

**Comment by ryan-kingstone** [comment]
I don't think the file can chmod itself. Need ideas for solution.

**Comment by bakpakin** [comment]
My bad, I titled the issue wrong. I need to chmod the love executable in the bin folder, so it should be 'chmod +x bin/x64/macosx-x64/love.app/Contents/MacOS/love'

**Comment by andrewmcwatters** [comment]
On a clean install of Mac OS X and a clone to anywhere in my user directory, I've never needed to do this. I don't really know what to do about this, because I'm assuming you might be cloning to a directory where permissions prohibit this, but it's outside of the scope of what the shell scripts do.

You guys hit me up if we have a solution to this, otherwise I `cantfix`(?)
